export * from './Home'
export * from './Login'
export { default as Feedback } from './Feedback'
export { default as Resources } from './Resources'
export { default as Meetings } from './Meetings/Meetings'
export { default as Payments } from './Payments/Payments'
export { default as Homeworks } from './Homeworks/Homeworks'
