export * from './Home'
export * from './Login'
export { default as Report } from './Report/Report'
export { default as Feedbacks } from './Feedbacks/Feedbacks'
export { default as Resources } from './Resources'
export { default as Meetings } from './Meetings/Meetings'
export { default as Payments } from './Payments/Payments'
export { default as Homeworks } from './Homeworks/Homeworks'
export { default as UnPaid } from './UnPaid/UnPaid'
