export * as MeetingsController from './meetings.controller'
export * as PaymentsController from './payments.controller'
export * as HomeworksController from './homeworks.controller'
export * as AuthController from './auth.controller'
export * as UsersController from './users.controller'
export * as FeedbackController from './feedback.controller'
